### ISSUE TITLE
Getting Error on installing in Blender

### ISSUE THREAD

**Issue by TDOlmstead** [mrachinskiy/blender-addon-jewelcraft#1]
I was installing your three repos and had no trouble with Commotion & Booltron yet Jewelcraft gives me the following Error:
![screenhunter_168 jan 15 14 56](https://cloud.githubusercontent.com/assets/4634466/12365271/6f549fc4-bb99-11e5-99e4-da1953a5f38b.jpg)

I am on Windows 7 X64, Blender 2.74

Your addons look amazing looking forward to using them.

Thx, Tracy

**Comment by mrachinskiy** [comment]
Hi Tracy,

JewelCraft does not support Blender 2.74 and below, it will only work with Blender 2.75 and above. Could you please try to use Blender 2.76b?

By the way, it's says it right there: https://github.com/mrachinskiy/blender-addon-jewelcraft#how-to-install

**Comment by TDOlmstead** [comment]
I must have missed that.  It installs and work fine after I updated to
2.7.6.  Thank you for all your add-on work.  Looking forward to following
you on G+.

Thanks for the quick response,

Tracy
