### ISSUE TITLE
error add on

### ISSUE THREAD

**Issue by max1r** [mrachinskiy/blender-addon-jewelcraft#2]
hello,

 i try to install jewelers 1.3 on blender 2.76.4 

and an error appear, where is the problem?

Thank You very much for amazing add on

![cattura](https://cloud.githubusercontent.com/assets/16742626/12377077/24166d44-bd10-11e5-97b2-0c6e527551af.PNG)

**Comment by mrachinskiy** [comment]
Hi,

How do you install it?

**Comment by max1r** [comment]
I install the zip folder (without extracting) from user preferences.

2016-01-17 11:57 GMT+01:00 Mikhail Rachinskiy <notifications@github.com>:

**Comment by mrachinskiy** [comment]
I guess it might be the system locale, could you please do the following:
1. Download [Blender zip](https://www.blender.org/download/)
2. Unpack in `C:\` folder (like so: `C:\blender_folder`)
3. Create empty folder `config` like so: `C:\blender_folder\2.76\config`
4. Unpack JewelCraft zip and move `blender-addon-jewelcraft-master` folder in to: `C:\blender_folder\2.76\scripts\addons\`
5. Run blender: `C:\blender_folder\blender.exe` and enable JewelCraft add-on.
6. If it gives an error, save user settings: `File → User Preferences → Save User Settings`, close and open Blender again

And tell me results.

**Comment by max1r** [comment]
Now it works,

 Thanks a lot for the help.

2016-01-17 12:40 GMT+01:00 Mikhail Rachinskiy <notifications@github.com>:
