### ISSUE TITLE
Dimension of the stones 

### ISSUE THREAD

**Issue by olbaye** [mrachinskiy/blender-addon-jewelcraft#3]
Hello,

First I would like to thank you for your jewelscraft addon. It very usefull and well done.
I just have one question : How can i give a dimension to the stone when i've choosen the cut. 

For example I choose an aquamarin in an emerald cut. I can give one dimension (the lenght for e.x) but i don't know how to give the other dimensions of the stones, like the thickness and the breadth ?

Thanks in advance for your help.
Best regards,

Olivier
olibaye@gmail.com

**Comment by mrachinskiy** [comment]
Hi Olivier,

After you created the stone, press N to evoke properties panel, there you can find Dimensions property of the active object in the Transform group.

**Comment by olbaye** [comment]
Hi 

Super ! Thank you for your very quick answer. It's logical, i didn't see it ;).

Wish you a good continuation.
